spring.application.name=backEnd
spring.datasource.url=${DB_URL}
spring.datasource.username=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false
front.end.url=${FRONT_END_URL}
#logging.level.org.springframework.security=trace

spring.ai.openai.api-key=${OPENAI_API_KEY}
openai.api.url=${OPENAI_API_URL}
openai.model=gpt-4.1-mini