spring.application.name=backEnd
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false
front.end.url=http://localhost:5173